FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY *.sln .

COPY src/Sistema.API/*.csproj ./src/Sistema.API/
COPY src/Sistema.Application/*.csproj ./src/Sistema.Application/
COPY src/Sistema.Domain/*.csproj ./src/Sistema.Domain/
COPY src/Sistema.Infrastructure/*.csproj ./src/Sistema.Infrastructure/

RUN dotnet restore

COPY . .

WORKDIR /app/src/Sistema.API

RUN dotnet publish -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

COPY --from=build /publish .

ENV ASPNETCORE_URLS=http://+:10000
EXPOSE 10000

ENTRYPOINT ["dotnet", "Sistema.API.dll"]