FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY *.sln .

COPY Sistema.API/*.csproj ./Sistema.API/
COPY Sistema.Application/*.csproj ./Sistema.Application/
COPY Sistema.Domain/*.csproj ./Sistema.Domain/
COPY Sistema.Infrastructure/*.csproj ./Sistema.Infrastructure/

RUN dotnet restore

COPY . .

WORKDIR /app/Sistema.API

RUN dotnet publish -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

COPY --from=build /publish .

ENV ASPNETCORE_URLS=http://+:10000
EXPOSE 10000

ENTRYPOINT ["dotnet", "Sistema.API.dll"]